name: Web CI/CD

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - 'apps/web/**'

permissions:
  deployments: write

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Linting
        run: pnpm --filter ./apps/web lint

  deploy-to-dev:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: |
          cd apps/web
          pnpm dlx nuxi build --preset=cloudflare_pages

      - name: Deploy To Dev Environment
        run: |
          cd apps/web
          pnpm add -g wrangler
          wrangler pages deploy --project-name=lisansly-dev-website dist/
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-to-production:
    needs:
      - deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: |
          cd apps/web
          pnpm dlx nuxi build --preset=cloudflare_pages

      - name: Deploy To Production Environment
        run: |
          cd apps/web
          pnpm add -g wrangler
          wrangler pages deploy --project-name=lisansly-prod-website dist/
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
