name: Account CI/CD

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - 'apps/account/**'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Linting
        run: pnpm --filter="./apps/account" lint

  deploy-to-dev:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter="./apps/account" build
        env:
          NITRO_PRESET: cloudflare

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy To Development Environment
        run: |
          cd apps/account
          wrangler deploy --name=lisansly-dev-account
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-to-prod:
    needs:
      - deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter="./apps/account" build
        env:
          NITRO_PRESET: cloudflare

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy To Production Environment
        run: |
          cd apps/account
          wrangler deploy --name=lisansly-prod-account
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
