name: UI Package Triggers To Apps Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/ui/**'

jobs:
  call-app-web-workflow:
    uses: ./.github/workflows/app-web.yaml

  call-app-account-workflow:
    uses: ./.github/workflows/app-account.yaml
